### ISSUE TITLE
起点中文网vip章节乱码

### ISSUE THREAD

**Issue by YanceyChiew** [deepink-app/booksource#46]
起点中文网的vip章节虽然网页版渲染出来是正确的，但它实际对部分字符使用了编码加偏，再配合经过相同加偏的专用字体来显示，所以直接获取网页文本内容会出现大量字符无法渲染，而显示缺字符的情况。
没有深入探究加偏的字体是从云端直接下载的还是本地临时生成的，但可以肯定的是该字体有很多套，往往一章之类使用了多个不同编号的加偏字体，这些字体以base64编码的形式直接存在于html文档中。

**Comment by YanceyChiew** [comment]
奇怪，刚重新登陆又试了下，又显示了原始文本没有进行加偏，看来还有随机性

**Comment by chimisgo** [comment]
目前起点似乎是时而加密时而明文。
